conky.config = {
    alignment = 'top_right',
    display = 0,
    background = false,
    xftalpha = 1.0,
    border_width = 1,
    gap_x = 2570,
    gap_y = -220,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'black',
    default_shade_color = 'black',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=10',
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = false,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 150,
    own_window_colour = 'black',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 5,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

conky.text = [[
    ${color white}$alignc$sysname $kernel on $machine
    ${color white}$alignc${exec whoami} @ $nodename

    $color$stippled_hr
    ${color}Date: ${color white}${time %A,%d %B}
    ${color}Time: ${color white}${time %k:%M:%S}${alignr}${color}Uptime: ${color white}$uptime
    $color$stippled_hr
    ${alignc} Temps: CPU: ${color white}${exec sensors | grep 'Tctl' | awk '{print $2}'}$color - GPU: ${color white}${exec sensors | grep junction  | awk '{print $2}'}
    $color$stippled_hr
    ${color}CPU:${color white} $cpu%  ${cpubar $cpu%}
    ${color}RAM:${color white} $memperc%  $mem/$memmax $membar
    ${color}Swap: ${color white}$swapperc% $swap/$swapmax ${swapbar}
    ${color}CPU governor: ${color white}${cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor}
    $color$stippled_hr
    ${color}Top Processes:
    ${color white}Name               CPU%   MEM%  USER
    ${color}${top name 1} ${top cpu 1} ${top mem 1}  ${top user 1}
    ${color}${top name 2} ${top cpu 2} ${top mem 2}  ${top user 2}
    ${color}${top name 3} ${top cpu 3} ${top mem 3}  ${top user 3}
    ${color}${top name 4} ${top cpu 4} ${top mem 4}  ${top user 4}
    ${color}${top name 5} ${top cpu 5} ${top mem 5}  ${top user 5}
]]

